// Angular/src/app/calculator/calculator.component.ts
import {ChangeDetectionStrategy, Component, OnInit} from '@angular/core';
import { CalculatorService } from "./services/calculator.service";
import { OperationTypes } from "./enums/operation-types.enum";
import {FormBuilder, FormControl, FormGroup, UntypedFormBuilder, Validators} from "@angular/forms";

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalculatorComponent implements OnInit{
  readonly operationTypes = OperationTypes;
  calculatorForm: FormGroup<{
    selectedOperation: FormControl<OperationTypes>;
    firstNumber: FormControl<number>;
    secondNumber: FormControl<number>;
  }>;
  result: number | null = null;

  constructor(private formBuilder: UntypedFormBuilder, private calculatorService: CalculatorService) {}


  ngOnInit(): void {
    this.calculatorForm = this.formBuilder.group({
      selectedOperation: [OperationTypes.Add, [Validators.required]],
      firstNumber: [0, [Validators.required]],
      secondNumber: [0, [Validators.required]],
    });
  }

  calculate(): void {
    const { selectedOperation, secondNumber, firstNumber} = this.calculatorForm.controls;
    switch (selectedOperation.value) {
      case OperationTypes.Add:
        this.result = this.calculatorService.getSum([firstNumber.value, secondNumber.value]);
        break;
      case OperationTypes.Multiply:
        this.result = this.calculatorService.getMultiple([firstNumber.value, secondNumber.value]);
        break;
    }
  }
}

<div class="calculator" [formGroup]="calculatorForm">
  <h1 class="calculator__title">Calculator</h1>

  <div class="calculator__operation">
    <label class="calculator__radio-label">
      <input id="add-operation" type="radio" name="selectedOperation" [value]="operationTypes.Add" formControlName="selectedOperation" class="calculator__radio-input" /> Addition
    </label>
    <label class="calculator__radio-label">
      <input id="multiply-operation" type="radio" name="selectedOperation" [value]="operationTypes.Multiply" formControlName="selectedOperation" class="calculator__radio-input" /> Multiplication
    </label>
  </div>

  <div class="calculator__input-group">
    <label class="calculator__label">First Number:</label>
    <input type="number" formControlName="firstNumber"  class="calculator__input" />
  </div>

  <div class="calculator__input-group">
    <label class="calculator__label">Second Number:</label>
    <input type="number" formControlName="secondNumber"  class="calculator__input" />
  </div>

  <button (click)="calculate()" class="calculator__button">Calculate</button>

  <div class="calculator__result" *ngIf="result !== null">
    <p class="calculator__result-text">Result: {{ result }}</p>
  </div>
</div>

// React/CalcApp/src/app/calculator/calculator.tsx
import styles from './calculator.module.scss';
import React, { useState } from 'react';
import { getSum, getMultiple } from '../helpers/helper';

export function Calculator() {
  const [selectedOperation, setSelectedOperation] = useState('add');
  const [firstNumber, setFirstNumber] = useState(0);
  const [secondNumber, setSecondNumber] = useState(0);
  const [result, setResult] = useState(0);

  const calculate = () => {
    if (selectedOperation === 'add') {
      const sum = getSum([firstNumber, secondNumber]);
      setResult(sum);
    } else if (selectedOperation === 'multiply') {
      getMultiple([firstNumber, secondNumber]);
      setResult(firstNumber * secondNumber);
    }
  };

  return (
    <div className={ styles.calculator }>
      <h2 className={ styles.calculator__title }>Calculator</h2>
      
      <div className={ styles.calculator__operation }>
        <label className={ styles.calculator__radio_label }>
          <input type="radio" name="operation" value="add" checked={selectedOperation === 'add'} onChange={() => setSelectedOperation('add')} className={ styles.calculator__radio_input } /> Addition
        </label>
        <label className={ styles.calculator__radio_label }>
          <input type="radio" name="operation" value="multiply" checked={selectedOperation === 'multiply'} onChange={() => setSelectedOperation('multiply')} className={ styles.calculator__radio_input } /> Multiplication
        </label>
      </div>
      
      <div className={ styles.calculator__input_group }>
        <label className={ styles.calculator__label }>First Number:</label>
        <input type="number" value={firstNumber} onChange={e => setFirstNumber(Number(e.target.value))} className={ styles.calculator__input } />
      </div>
      
      <div className={ styles.calculator__input_group }>
        <label className={ styles.calculator__label }>Second Number:</label>
        <input type="number" value={secondNumber} onChange={e => setSecondNumber(Number(e.target.value))} className={ styles.calculator__input } />
      </div>
      
      <button onClick={calculate} className={ styles.calculator__button }>Calculate</button>
      
      {result !== null && (
        <div className={ styles.calculator__result }>
          <p className={ styles.calculator__result_text }>Result: {result}</p>
        </div>
      )}
    </div>
  );
}

export default Calculator;
